name: 'Terraform - Production'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  id-token: write
  pull-requests: write
  statuses: write
  actions: read
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
           role-to-assume: ${{ secrets.CI_ROLE }}
           aws-region: "us-west-2"
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pyhcl
      
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y wget
          wget https://github.com/tfsec/tfsec/releases/download/v0.58.5/tfsec-linux-amd64
          chmod +x tfsec-linux-amd64
          mv tfsec-linux-amd64 /usr/local/bin/tfsec
          wget https://github.com/open-policy-agent/opa/releases/download/v0.34.1/opa_linux_amd64
          chmod +x opa_linux_amd64
          mv opa_linux_amd64 /usr/local/bin/opa
          wget https://github.com/terraform-linters/tflint/releases/download/v0.30.0/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip
          mv tflint /usr/local/bin/tflint
        
      - name: execute py script 
        run: python lint.py
    
      - name: Terraform formate
        id: formate
        run: |
          terraform fmt -diff -write=true -recursive .
          terraform fmt
     
      #- name: Run tfsec
       # run: tfsec .
     
     # - name: Run OPA
       # run: |
        #  opa run -c policies terraform
      
     # - name: Run Terraform Scan
       # run: |
        #  tflint .
      
      - name: Terraform init
        id: init
        run: terraform init 
      
      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan
